# Generated by Django 4.1 on 2022-09-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('shoes', 'Shoes'), ('jacket', 'Jackets'), ('tshirt', 'Tshirts'), ('hoodies', 'Hoodies'), ('trousers', 'Trousers')], default='Shoes', max_length=8)),
                ('sex', models.CharField(choices=[('women', 'Women'), ('men', 'Men')], default='Women', max_length=5)),
                ('trending', models.BooleanField(default=False)),
                ('collection', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('sale', models.IntegerField(default=0)),
            ],
        ),
    ]
