# Generated by Django 4.1 on 2022-08-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clothing_image_clothing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothing',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothing',
            name='price',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clothing',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='sex',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men')], default='Women', max_length=5),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jacket', 'Jacket'), ('tshirt', 'Tshirt'), ('hoodies', 'Hoodies'), ('trousers', 'Trousers')], default='Shoes', max_length=8),
        ),
    ]
