# Generated by Django 4.1 on 2022-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clothing_collection_clothing_new_clothing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
