# Generated by Django 4.1 on 2022-08-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_clothing_image_alter_clothing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
