# Generated by Django 4.1 on 2022-09-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
