# Generated by Django 4.1.1 on 2022-10-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0002_alter_clothing_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favourites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='clothing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clothing.clothing'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
