# Generated by Django 4.1 on 2022-09-11 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingApi', '0002_alter_clothing_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favourites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
    ]
