# Generated by Django 4.1 on 2022-09-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favourites', '0002_rename_favourites_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='clothing_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
