# Generated by Django 4.1 on 2022-09-11 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingApi', '0002_alter_clothing_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favourites', '0003_alter_favourite_clothing_id_alter_favourite_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='clothing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClothingApi.clothing'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
