# Generated by Django 4.1 on 2022-09-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favourites', '0004_alter_favourite_clothing_id_alter_favourite_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='clothing_id',
            field=models.IntegerField(default=0),
        ),
    ]
