# Generated by Django 4.1 on 2022-09-12 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingApi', '0002_alter_clothing_id'),
        ('Favourites', '0005_alter_favourite_clothing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='clothing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClothingApi.clothing'),
        ),
    ]
