# Generated by Django 4.1 on 2022-09-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favourites', '0006_alter_favourite_clothing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='clothing_id',
            new_name='clothing',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user_id',
            new_name='user',
        ),
    ]
