# Generated by Django 4.1 on 2022-09-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favourites', '0007_rename_clothing_id_favourite_clothing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='clothing',
            new_name='clothing_id',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='user_id',
        ),
    ]
