# Generated by Django 4.0.4 on 2022-09-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favourites', '0008_rename_clothing_favourite_clothing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
