# Generated by Django 4.0.4 on 2022-09-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favourites', '0009_alter_favourite_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='clothing_id',
            field=models.IntegerField(default=0),
        ),
    ]
