# Generated by Django 4.1 on 2022-09-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
