# Generated by Django 4.1.1 on 2022-10-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
