# Generated by Django 4.1 on 2022-09-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_user_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourites',
        ),
    ]
