# Generated by Django 4.1 on 2022-09-08 20:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_alter_user_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=jsonfield.fields.JSONField(),
        ),
    ]
