# Generated by Django 4.1 on 2022-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_alter_user_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.JSONField(),
        ),
    ]
